spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      # Flyway gerencia o schema, o Hibernate apenas valida.
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    repair-on-error: true
    locations: classpath:db/migration

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace

spring-doc:
  paths-to-match:
    - /auth/**
    - /api/v1/**/**
  swagger-ui:
    use-root-path: true