spring:
  security:
      jwt:
        secret-key: ${JWT_SECRET_KEY:551VM4LcN284uYnv3MjDckhe9IQ6ta7/0jNwrvNqRz0=}
        expirationMs: ${JWT_EXPIRATION_MS:3600000} # 1 hora em milissegundos
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      # Flyway gerencia o schema, o Hibernate apenas valida.
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    repair-on-error: true
    locations:
      - classpath:db/migration
      - classpath:db/migration-dev

springdoc:
    api-docs:
      enabled: ${SWAGGER_API_DOCS_ENABLED:true}
    swagger-ui:
      url: /openapi.yml

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace