spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password: ""

  h2:
    console:
      enabled: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    jwt:
      secret-key: 551VM4LcN284uYnv3MjDckhe9IQ6ta7/0jNwrvNqRz0=

  flyway:
    repair-on-error: true
    locations:
      - classpath:db/migration
      - classpath:db/migration-dev

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, beans, prometheus
  endpoint:
    health:
      show-details: always

# Configuração do swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yml