spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # Em produção, o Flyway deve gerenciar o schema
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    out-of-order: false
    baseline-on-migrate: false