spring:
  application:
    name: Backend Arena Mafia

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000} # 1 hora
      refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:7} # 7 dias
      issuer: "arena-mafia-api"

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enable: true

# Configuração dos Logs
logging:
  level:
    root: info

resilience4j:
  ratelimiter:
    instances:
      # Regra restrita para operações sensíveis
      sensitiveOperationLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0

      # Regra para o login
      loginRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1m
        timeoutDuration: 0

      # Limite geral para tráfego
      globalLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1m
        timeoutDuration: 0
